### ISSUE TITLE
How Long Will The Cookie Work?

### ISSUE THREAD

**Issue by nflxplng** [Duocodies/DuoFlix#1]
Hello, I have a Telegram Channel and I would like to know how long the cookie will work as I'll have to depend on your Extension.
Please let me know.

**Comment by duoadmin** [comment]
This cookie won't expire unless someone makes a signout / Or after the expiry time of cookies whichever is earliest.

**Comment by nflxplng** [comment]
> This cookie won't expire unless someone makes a signout / Or after the expiry time of cookies whichever is earliest.

May I know when the cookie would expire?
Because I would need it up and running for at least a month. Also, Will the cookie continue working if it's made through a server that is up 24/7?
Please help me with the information, Because what you've got here is AMAZING, And I would really want to know more about it before I start using it as the main thing.

**Comment by duoadmin** [comment]
> > It won't expire unless you logout from the server or anyone that uses your cookie logouts.
> 
> Oh Okay. Lately it has been expiring. So will check Thanks for the reply.

It is expiring because I have added a module for it to expire whenever someone removes the extension

**Comment by MunkasirMahir** [comment]
dude...why is your website(duocodies.ml) not functioning???  Do i have to use vpn or something else??

**Comment by duoadmin** [comment]
> dude...why is your website(duocodies.ml) not functioning??? Do i have to use vpn or something else??

the website is not functional as of now
